create table public.open_weeks (
  id bigint generated by default as identity primary key,
  week_start_date date not null unique,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table public.open_slots (
  id uuid primary key default gen_random_uuid(),
  open_week_id bigint not null references public.open_weeks(id) on delete cascade,
  available_date date not null,
  start_time time not null,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique (available_date, start_time)
);

create index if not exists idx_open_slots_open_week_id on public.open_slots (open_week_id);
create index if not exists idx_open_slots_available_date on public.open_slots (available_date);

alter table public.open_weeks enable row level security;
alter table public.open_slots enable row level security;

create policy "public reads future open slots" on public.open_slots for select using (available_date >= current_date);
create policy "staff open weeks" on public.open_weeks for all using (public.is_admin()) with check (public.is_admin());
create policy "staff open slots" on public.open_slots for all using (public.is_admin()) with check (public.is_admin());
